### ISSUE TITLE
playground运行，开启debug后崩溃

### ISSUE THREAD

**Issue by yzz413026** [apache/incubator-weex-playground#26]
03-19 17:25:33.016   997  1132 E AndroidRuntime: FATAL EXCEPTION: WeexJSBridgeThread
03-19 17:25:33.016   997  1132 E AndroidRuntime: Process: org.apache.weex, PID: 997
03-19 17:25:33.016   997  1132 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void com.taobao.weex.common.IWXBridge.setPageArgument(java.lang.String, java.lang.String, java.lang.String)"
03-19 17:25:33.016   997  1132 E AndroidRuntime: 	at com.taobao.weex.bridge.WXBridgeManager$18.run(WXBridgeManager.java:1571)
03-19 17:25:33.016   997  1132 E AndroidRuntime: 	at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:70)
03-19 17:25:33.016   997  1132 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
03-19 17:25:33.016   997  1132 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-19 17:25:33.016   997  1132 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:192)
03-19 17:25:33.016   997  1132 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by cnryb** [comment]
请尝试使用源码集成的方式。是playground里面使用老版本的 inspector 里没有新添加的接口setPageArgument导致的。

**Comment by yzz413026** [comment]
源码集成也尝试过，还是报同样的错误 @cnryb

**Comment by cnryb** [comment]
你把这里的版本号，换成 0.28.0-alpha-1 ，试试看。
https://github.com/apache/incubator-weex-playground/blob/master/android/playground/build.gradle#L111

**Comment by yzz413026** [comment]
现在不会报错了，但是也没有debug成功，网页中没有反应。我是按官方文档第一种方式启动：
 private void initDebugEnvironment(boolean enable, String host) {
        WXEnvironment.sRemoteDebugMode = enable;
        WXEnvironment.sRemoteDebugProxyUrl =   "ws://169.254.187.40:8089/debugProxy/native";
        WXEnvironment.sApplication = this;
    }
    WXSDKEngine.initialize(this, config);
    load(bundleUrl, null);
@cnryb

**Comment by cnryb** [comment]
首先要确保手机和你电脑的网络是联通的。 另外，看起来你拼接的 ws 地址少了一截。你可以看看扫码启动调试的逻辑。

**Comment by yzz413026** [comment]
多谢。我用手机试同一wifi过，然后不行又也用了模拟器。ws是少了一截。我一开始是用完整的，也不行，说明里面是这样的所以就去掉试了下。扫描启动调试的入口是哪个类，我去看看 
@cnryb

**Comment by yzz413026** [comment]
是必须用sdk_legacy版本？我发现是反射的IWXDebugConfig包名不一致，debugproxy没有启动
